// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc348.RecycleRushForklift.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc348.RecycleRushForklift.Robot;

/**
 *
 */
public class  HomeElevatorCommand extends Command {

	private boolean delayStarted = false;
	private boolean finished = false;
	private Timer bottomWaitTimer = new Timer();
	
    public HomeElevatorCommand() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	delayStarted = false;
    	finished = false;
    	bottomWaitTimer.stop();
    	bottomWaitTimer.reset();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.elevator.disable();
    	if(delayStarted)
    	{
    		if(bottomWaitTimer.get() > 0.3)
    		{
    			Robot.elevator.resetEncoder();
    			finished = true;
    		}
    	}
    	else if (Robot.elevator.isAtLowerLimit()){
    		Robot.elevator.stop();
    		delayStarted = true;
    		bottomWaitTimer.start();
    	}
    	else {
    		Robot.elevator.driveDownSlowly();
    	}
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return finished;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
