// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc348.RecycleRushForklift.subsystems;

import java.awt.Robot;

import org.usfirst.frc348.RecycleRushForklift.RobotMap;
import org.usfirst.frc348.RecycleRushForklift.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Vacuum extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController vacuumPumpMotor = RobotMap.vacuumVacuumPumpMotor;
    AnalogInput vacuumSensor = RobotMap.vacuumVacuumSensor;
    Servo vacuumJawValveServo = RobotMap.vacuumVacuumJawValveServo;
    Servo vacuumArmValveServo = RobotMap.vacuumVacuumArmValveServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void ActivatePump() {
    	double pumpSpeed = RobotMap.prefs.getDouble("Vacuum_OpenLoopPumpSpeedCommand", 0.7);
    	
    	vacuumPumpMotor.set(pumpSpeed);
    }
    
    public void DeactivatePump() {
    	vacuumPumpMotor.set(0);
    }
    
    public void ActivateJawVacuum() {
    }
    }

